name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Add SSH keyscan
      run: |
        ssh-keyscan -p 30 13.58.67.97 >> ~/.ssh/known_hosts

    - name: Copy files to EC2
      run: |
        scp -r -P 30 -o StrictHostKeyChecking=no * ubuntu@13.58.67.97:/var/www/html/mk

    - name: Deploy backend with Docker Compose
      run: |
        ssh -p 30 -o StrictHostKeyChecking=no ubuntu@13.58.67.97 << 'EOF'
        cd /var/www/html/mk/
        docker-compose down
        docker-compose up -d --build
        EOF

    - name: Deploy admin frontend
      run: |
        ssh -p 30 -o StrictHostKeyChecking=no ubuntu@13.58.67.97 << 'EOF'
        cd /var/www/html/mk/admin-frontend-next
        npm install
        npm run build
        npm run start
        EOF

    - name: Deploy client frontend
      run: |
        ssh -p 30 -o StrictHostKeyChecking=no ubuntu@13.58.67.97 << 'EOF'
        cd /var/www/html/mk/client-frontend-next
        npm install
        npm run build
        npm run start
        EOF
